### ISSUE TITLE
How can I change 'vertical swipe' state into 'swiped' dynamically?

### ISSUE THREAD

**Issue by whitebunny890202** [Rewieer/react-native-vertical-swipe#1]
I want to make verticalswipe show the second screen as initial state. In other word, I want vertial swipe to be swiped initially. How can I implement this?
I am sure it will be great if we can implement this using prop.

**Comment by Rewieer** [comment]
This sounds like a good idea, I will check this out and submit a PR when I find time for it !

**Comment by whitebunny890202** [comment]
Thanks for your reply, Anthony.

Now I am in progress for social app development and we need your package.
I think, it is great, but there is one problem. We want to make initial state as the second.
I hope good result asap.

Regards. 
Bruno.

**Comment by Rewieer** [comment]
Check out the version 1.1.0. Use `startOpened` prop set to true :)
I've been working out this plugin for my app in my own repository and copied the latest version, which handles going back in Android to close the swipe instead of closing the app, among some minor enhancement.

Tell me if it worked out for you, and don't hesitate to submit pull requests.
Regards.

**Comment by whitebunny890202** [comment]
Thanks very much.

I will try it now.

Bruno.

**Comment by whitebunny890202** [comment]
Hi, Anthony.

The second screen is displayed as initial state using startOpend but there is a problem.
Once I click the second screen, it disappears, not working as vertical swipe.
I hope your response as soon as possible.
I really appreciate for your help.

Regards.
Bruno.

**Comment by whitebunny890202** [comment]
Hi Anthony.

It works and I can set second screen as default.
But once I tap the second screen it disappeared immediately.
This is a problem, and I want it to work as normal(vertical swipe - not disappearing).
I hope your help as soon as possible.

Thanks.

**Comment by whitebunny890202** [comment]
Anthony, you have to change your code in "initialize" function like this

///original/////
this.state = {
      isAnimating: false,
      isOpen: false,
      position: new Animated.Value(this.props.startOpened === true ? this._openPosition : this._closedPosition),
    };

///after revision//////
this.state = {
      isAnimating: false,
      isOpen: this.props.startOpened,
      position: new Animated.Value(this.props.startOpened === true ? this._openPosition : this._closedPosition),
    };

**Comment by Rewieer** [comment]
Hello
I'm aware of that problem and have yet to solve it.
Please understand that i'm under a hard schedule and might not have time to do it right away

Thanks

**Comment by whitebunny890202** [comment]
Hi

I’ve solved it and provide answer on the GitHub issue.

Regard

**Comment by Rewieer** [comment]
I've run an update, please tell me if it solved your problem
Thanks
